
TYPE
	IncubatorStationStateEnum : 
		(
		INC_OFF,
		INC_STARTUP,
		INC_READY,
		INC_WAIT_SHUTTLE,
		INC_WAIT_REQUEST,
		INC_ERROR
		);
	AnalyzerStationStateEnum : 
		(
		ANALYZER_OFF,
		ANALYZER_STARTUP,
		ANALYZER_READY,
		ANALYZER_WAIT_SHUTTLE,
		ANALYZER_WAIT_REQUEST,
		ANALYZER_REQUEST_SAMPLE,
		ANALYZER_WAIT_PIPETTE_READY,
		ANALYZER_ERROR
		);
END_TYPE
